language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
gemfile:
  - test/gemfiles/rails-5.0
  - test/gemfiles/rails-5.1
  - test/gemfiles/rails-5.2
  - test/gemfiles/rails-6.0

notifications:
  recipients:
    email:
      - cedric@howe.net
  on_success: change
  on_failure: always
